### ISSUE TITLE
looks broken due to updated version and hardcoded packages

### ISSUE THREAD

**Issue by mo8Zomo0** [compujuckel/adsb-docker#2]
Building dump1090-fa
Step 1/21 : FROM debian:jessie
 ---> 0ac4637d440f
Step 2/21 : RUN apt-get update && 	apt-get install -y librtlsdr-dev fakeroot dpkg-dev git debhelper libusb-1.0-0-dev pkg-config dh-systemd libncurses5-dev libusb-1.0-0 build-essential cmake libtecla1 libtecla-dev wget doxygen help2man pandoc
 ---> Using cache
 ---> a1392f377668
Step 3/21 : RUN git clone --recursive https://github.com/Nuand/bladeRF.git
 ---> Using cache
 ---> 9a408f3f5475
Step 4/21 : WORKDIR bladeRF
 ---> Using cache
 ---> 96aeeecc4be7
Step 5/21 : RUN git checkout tags/2016.06
 ---> Using cache
 ---> 61728b3610e8
Step 6/21 : RUN dpkg-buildpackage -b
 ---> Using cache
 ---> 3acd78a9c10a
Step 7/21 : WORKDIR /
 ---> Using cache
 ---> d55285b1efc3
Step 8/21 : RUN dpkg -i libbladerf1_2016.06_amd64.deb libbladerf-dev_2016.06_amd64.deb
 ---> Using cache
 ---> 2399d4bb912b
Step 9/21 : RUN git clone https://github.com/flightaware/dump1090.git
 ---> Using cache
 ---> 3518058dfb1a
Step 10/21 : WORKDIR dump1090
 ---> Using cache
 ---> 7ab7680a37fe
Step 11/21 : RUN dpkg-buildpackage -b
 ---> Using cache
 ---> 38cc5730a866
Step 12/21 : FROM debian:jessie
 ---> 0ac4637d440f
Step 13/21 : COPY --from=0 libbladerf1_2016.06_amd64.deb .
 ---> Using cache
 ---> 0474ae821458
Step 14/21 : COPY --from=0 dump1090-fa_3.6.3_amd64.deb .
ERROR: Service 'dump1090-fa' failed to build: COPY failed: stat /var/lib/docker/overlay2/3941a9e2a5f3fa0c71edc86691c55d9b4641eafd45590c57a38c59790514d428/merged/dump1090-fa_3.6.3_amd64.deb: no such file or directory

**Comment by compujuckel** [comment]
Sorry for the late reply, in case you haven't fixed it yourself yet this is fixed in 637cb890edf692b09e2aff385104c2a5432a6ea7.
